version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - '3000:8080'
    environment:
      - OLLAMA_BASE_URL=https://text.pollinations.ai
      - WEBUI_AUTH=false
      - WEBUI_NAME=Mentat Party Chat
      - WEBUI_URL=http://localhost:3000
      - DEFAULT_MODELS=openai
      - ENABLE_SIGNUP=true
      - ENABLE_LOGIN=false
    volumes:
      - open-webui-data:/app/backend/data
    restart: unless-stopped
    networks:
      - mentat-network

networks:
  mentat-network:
    driver: bridge

volumes:
  open-webui-data:
